services:

  postgres:
    image: postgres:17

    container_name: fleet_postgres

    environment:
      POSTGRES_USER: fleetadmin
      POSTGRES_PASSWORD: fleetpass
      POSTGRES_DB: fleetdb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: